import type { Song } from "./types";

const WIKI = { label: "Wikipedia — Vannda", url: "https://en.wikipedia.org/wiki/Vannda" };
const BARAMEY = { label: "Baramey Production — VannDa", url: "https://baramey.com/vannda" };

export const songs: Song[] = [
  {
    slug: "mama",
    title: "MAMA",
    titleKm: "ម្តាយ",
    era: "skull",
    releaseYear: 2020,
    releaseDateLabel: "2020",
    albumSlug: "skull-the-album",
    featuring: ["Kmeng Khmer"],
    youtubeId: "WNL3zDgWZc0",
    youtubeChannel: "វណ្ណដា-VannDa Official",
    about:
      "An early single from VannDa's self-produced rise, released the same year as his debut album $kull the Album, paired with the group Kmeng Khmer.",
    fanInterpretation:
      "Fans often point to MAMA as one of the tracks where VannDa's melodic, ballad-rooted songwriting (from his earliest 2016–2018 releases) still shows through underneath the hip-hop production.",
    tags: ["single", "2020", "collaboration"],
    sources: [WIKI],
  },
  {
    slug: "time-to-rise",
    title: "Time To Rise",
    era: "breakthrough",
    releaseYear: 2021,
    releaseDateLabel: "2021",
    featuring: ["Master Kong Nay"],
    youtubeId: "rvje5oblrLw",
    youtubeChannel: "វណ្ណដា-VannDa Official",
    about:
      "VannDa's breakthrough single, built around a collaboration with chrieng chapei master Kong Nay — one of the few great masters of the genre to have survived the Khmer Rouge era. Originally created for a Cellcard marketing campaign, the music video was filmed at the National Museum of Cambodia and blends traditional chapei dang veng playing with modern hip-hop. In October 2022 it became the first music video by a Cambodian artist to pass 100 million YouTube views.",
    fanInterpretation:
      "For many Cambodian fans, this is the song that made Khmer hip-hop feel like it belonged on a world stage without leaving its own culture behind — Kong Nay's verses read as a literal passing of the torch to a new generation.",
    tags: ["single", "2021", "breakthrough", "collaboration", "traditional"],
    sources: [WIKI, BARAMEY],
  },
  {
    slug: "time",
    title: "Time",
    era: "breakthrough",
    releaseYear: 2021,
    releaseDateLabel: "2021",
    featuring: ["Sophia Kao"],
    youtubeId: "_1sdvk_8bYk",
    youtubeChannel: "Sophia Kao",
    about: "A collaboration with singer-songwriter Sophia Kao, released on her channel the same breakthrough year as Time To Rise.",
    tags: ["single", "2021", "collaboration"],
    sources: [WIKI],
  },
  {
    slug: "monsoon",
    title: "Monsoon",
    era: "breakthrough",
    releaseYear: 2021,
    releaseDateLabel: "2021",
    featuring: ["Songha"],
    youtubeId: "yMx-jKePx98",
    youtubeChannel: "វណ្ណដា-VannDa Official",
    about: "A collaboration with singer Songha released on VannDa's official channel during his 2021 breakthrough run.",
    tags: ["single", "2021", "collaboration"],
    sources: [WIKI],
  },
  {
    slug: "young-man",
    title: "Young Man",
    era: "skull2",
    releaseYear: 2022,
    releaseDateLabel: "2022",
    albumSlug: "skull-2-season-1",
    featuring: ["OG Bobby"],
    youtubeId: "nHXLfMeNoLA",
    youtubeChannel: "វណ្ណដា-VannDa Official",
    about: "VannDa's first collaboration with OG Bobby, released as part of the SKULL 2 (Season 1) era.",
    tags: ["single", "2022", "collaboration", "skull2"],
    sources: [WIKI],
  },
  {
    slug: "run-the-town",
    title: "Run The Town",
    era: "skull2",
    releaseYear: 2022,
    releaseDateLabel: "2022",
    featuring: ["F.HERO", "1MILL", "Sprite"],
    youtubeId: "UwE8RPbPmrI",
    youtubeChannel: "វណ្ណដា-VannDa Official",
    about:
      "A regional crossover single joining VannDa with Thai artists F.HERO and 1MILL, produced by High Cloud Entertainment.",
    tags: ["single", "2022", "collaboration", "regional"],
    sources: [WIKI],
  },
  {
    slug: "coda",
    title: "C.O.D.A",
    era: "skull2",
    releaseYear: 2022,
    releaseDateLabel: "2022",
    albumSlug: "skull-2-season-1",
    featuring: [],
    youtubeId: "VYLM-vpdQ1A",
    youtubeChannel: "វណ្ណដា-VannDa Official",
    about: "\"C.O.D.A\" (Culture Of Devoted Aspiration) — a key track from SKULL 2 (Season 1), VannDa's sophomore full-length album.",
    tags: ["album-track", "2022", "skull2"],
    sources: [WIKI],
  },
  {
    slug: "baby-mama",
    title: "Baby Mama",
    era: "skull2",
    releaseYear: 2022,
    releaseDateLabel: "2022",
    featuring: [],
    youtubeId: "Jbt5dRYFOPo",
    youtubeChannel: "វណ្ណដា-VannDa Official",
    about: "A single released on VannDa's official channel during the SKULL 2 era.",
    tags: ["single", "2022"],
    sources: [WIKI],
  },
  {
    slug: "khmer-gentlemen",
    title: "Khmer Gentlemen",
    titleKm: "កម្លោះស្រុកខ្មែរ",
    era: "baramey-crew",
    releaseYear: 2023,
    releaseDateLabel: "2023",
    featuring: ["Vanthan"],
    youtubeId: "fJuJ6GW0UEk",
    youtubeChannel: "Vanthan - វណ្ណថាន Official",
    about: "A collaboration with fellow Baramey Production artist Vanthan, released on Vanthan's official channel.",
    tags: ["single", "2023", "collaboration", "baramey"],
    sources: [WIKI],
  },
  {
    slug: "legacy",
    title: "Legacy",
    titleKm: "ចងចាំសាវតារ",
    era: "baramey-crew",
    releaseYear: 2023,
    releaseDateLabel: "2023",
    featuring: ["Baramey Crew"],
    youtubeId: "StNAenr4rVY",
    youtubeChannel: "Baramey Official",
    about:
      "A posse cut released under the Baramey Crew banner, bringing together artists from the Baramey Production roster.",
    tags: ["single", "2023", "collaboration", "baramey"],
    sources: [WIKI],
  },
  {
    slug: "sangkran-magic",
    title: "Sangkran Magic",
    titleKm: "សង្រ្កាន្តស្គាល់ស្នេហ៍",
    era: "baramey-crew",
    releaseYear: 2023,
    releaseDateLabel: "2023",
    featuring: [],
    youtubeId: "Cpo3DmbdCxs",
    youtubeChannel: "វណ្ណដា-VannDa Official",
    about: "A single released around Khmer New Year (Sangkran), released on VannDa's official channel.",
    tags: ["single", "2023", "cultural"],
    sources: [WIKI],
  },
  {
    slug: "blue-story",
    title: "Blue Story",
    era: "baramey-crew",
    releaseYear: 2023,
    releaseDateLabel: "2023",
    featuring: [],
    youtubeId: "0jSgcE-sxeo",
    youtubeChannel: "វណ្ណដា-VannDa Official",
    about: "A single released on VannDa's official channel.",
    tags: ["single", "2023"],
    sources: [WIKI],
  },
  {
    slug: "day-dreamer",
    title: "Day Dreamer",
    titleKm: "សុបិនទាំងថ្ងៃ",
    era: "baramey-crew",
    releaseYear: 2023,
    releaseDateLabel: "2023",
    featuring: [],
    youtubeId: "KyrXi-q2bBY",
    youtubeChannel: "វណ្ណដា-VannDa Official",
    about: "A single released on VannDa's official channel.",
    tags: ["single", "2023"],
    sources: [WIKI],
  },
  {
    slug: "6-years-in-the-game",
    title: "6 Years In The Game",
    era: "global",
    releaseYear: 2024,
    releaseDateLabel: "2024",
    featuring: ["Awich"],
    youtubeId: "UAoI1SyWprI",
    youtubeChannel: "វណ្ណដា-VannDa Official",
    about:
      "A collaboration with Japanese rapper Awich, marking six years since VannDa's first hip-hop releases and part of his growing run of international collaborations.",
    tags: ["single", "2024", "collaboration", "international"],
    sources: [WIKI],
  },
  {
    slug: "out-of-my-mind",
    title: "Out Of My Mind",
    era: "treyvisai",
    releaseYear: 2025,
    releaseDateLabel: "March 14, 2025",
    albumSlug: "treyvisai-i",
    featuring: [],
    youtubeId: "aSOuRMyxdNA",
    youtubeChannel: "វណ្ណដា-VannDa Official",
    about: "A high-energy opener from TREYVISAI I: The Search for Light, the first installment of VannDa's 2025 mini-album trilogy.",
    tags: ["album-track", "2025", "treyvisai"],
    sources: [{ label: "Bandwagon Asia", url: "https://www.bandwagon.asia/articles/vannda-takes-no-disrespect-drops-2nd-installment-of-treyvisai-mini-album-trilogy-burn-like-the-sun" }],
  },
  {
    slug: "fishing",
    title: "Fishing",
    era: "treyvisai",
    releaseYear: 2025,
    releaseDateLabel: "March 14, 2025",
    albumSlug: "treyvisai-i",
    featuring: [],
    youtubeId: "R5Lx2xCwsJQ",
    youtubeChannel: "វណ្ណដា-VannDa Official",
    about: "A track from TREYVISAI I: The Search for Light.",
    tags: ["album-track", "2025", "treyvisai"],
    sources: [{ label: "Bandwagon Asia", url: "https://www.bandwagon.asia/articles/vannda-takes-no-disrespect-drops-2nd-installment-of-treyvisai-mini-album-trilogy-burn-like-the-sun" }],
  },
  {
    slug: "no-disrespect",
    title: "No Disrespect",
    era: "treyvisai",
    releaseYear: 2025,
    releaseDateLabel: "March 21, 2025",
    albumSlug: "treyvisai-ii",
    featuring: [],
    youtubeId: "7t0qrQ0o42M",
    youtubeChannel: "វណ្ណដា-VannDa Official",
    about:
      "The lead single from TREYVISAI II: Burn Like the Sun, the second installment of VannDa's 2025 mini-album trilogy — its Khmer title translates to \"the compass.\"",
    tags: ["single", "2025", "treyvisai"],
    sources: [{ label: "Bandwagon Asia", url: "https://www.bandwagon.asia/articles/vannda-takes-no-disrespect-drops-2nd-installment-of-treyvisai-mini-album-trilogy-burn-like-the-sun" }],
  },
  {
    slug: "golden-land",
    title: "Golden Land",
    titleKm: "សុវណ្ណភូមិ",
    era: "treyvisai",
    releaseYear: 2025,
    releaseDateLabel: "2025",
    featuring: [],
    youtubeId: "jFVfxBQjMFU",
    youtubeChannel: "វណ្ណដា-VannDa Official",
    about: "A single from VannDa's TREYVISAI era, released on his official channel.",
    tags: ["single", "2025", "treyvisai", "cultural"],
    sources: [WIKI],
  },
  {
    slug: "asian-state-of-mind",
    title: "Asian State Of Mind",
    era: "global",
    releaseYear: 2025,
    releaseDateLabel: "2025",
    featuring: ["Awich", "Jay Park", "KR$NA", "Masiwei"],
    youtubeId: "QRnO04UwnM0",
    youtubeChannel: "Awich",
    about:
      "A pan-Asian posse cut produced by Diego Ave, bringing together Awich (Japan), Jay Park (Korea/USA), KR$NA (India), Masiwei (China), and VannDa (Cambodia) on one track.",
    tags: ["single", "2025", "collaboration", "international"],
    sources: [WIKI],
  },
];
