import type { Song, Source } from "./types";

const WIKI: Source = { label: "Wikipedia — Vannda", url: "https://en.wikipedia.org/wiki/Vannda" };
const BARAMEY: Source = { label: "Baramey Production — VannDa", url: "https://baramey.com/vannda" };

const SKULL_ALBUM_SOURCES: Source[] = [
  { label: "Deezer — $kull the Album", url: "https://www.deezer.com/en/album/156253922" },
  { label: "Apple Music — $kull the Album", url: "https://music.apple.com/us/album/$kull-the-album/1800389469" },
];
const SKULL2_SOURCES: Source[] = [
  { label: "Deezer — SKULL 2 (Season 1)", url: "https://www.deezer.com/en/album/722944861" },
  { label: "Apple Music — SKULL 2 (Season 1)", url: "https://music.apple.com/us/album/skull-2-season-1/1800385068" },
];
const TREYVISAI1_SOURCES: Source[] = [
  { label: "Spotify — TREYVISAI I", url: "https://open.spotify.com/album/0POR2y1NHYcgp4rQcBefw2" },
  { label: "Apple Music — TREYVISAI I", url: "https://music.apple.com/am/album/treyvisai-i-the-search-for-light/1799340902" },
];
const TREYVISAI2_SOURCES: Source[] = [
  { label: "Spotify — TREYVISAI II", url: "https://open.spotify.com/album/50FfMzzXAiUYYbIrUvRT8V" },
  {
    label: "Bandwagon Asia",
    url: "https://www.bandwagon.asia/articles/vannda-takes-no-disrespect-drops-2nd-installment-of-treyvisai-mini-album-trilogy-burn-like-the-sun",
  },
];
const TREYVISAI3_SOURCES: Source[] = [
  { label: "Spotify — TREYVISAI III", url: "https://open.spotify.com/album/3021zdV9VijgzqliBSid8n" },
  {
    label: "Apple Music — TREYVISAI III",
    url: "https://music.apple.com/us/album/treyvisai-iii-return-to-sovannaphum/1811895318",
  },
];

export const songs: Song[] = [
  // ───────────────────────── $kull the Album (2020-06-19) ─────────────────────────
  {
    slug: "demon",
    title: "Demon",
    category: "album-track",
    era: "skull",
    releaseYear: 2020,
    releaseDateLabel: "June 19, 2020",
    albumSlug: "skull-the-album",
    trackNumber: 1,
    durationSeconds: 253,
    featuring: [],
    youtubeId: "5ADvxgTGaJo",
    youtubeChannel: "វណ្ណដា-VannDa Official",
    about: "The opening track of VannDa's debut album, $kull the Album.",
    tags: ["album-track", "2020", "skull"],
    sources: SKULL_ALBUM_SOURCES,
  },
  {
    slug: "out-da-mud",
    title: "Out Da Mud",
    category: "album-track",
    era: "skull",
    releaseYear: 2020,
    releaseDateLabel: "June 19, 2020",
    albumSlug: "skull-the-album",
    trackNumber: 2,
    durationSeconds: 197,
    featuring: ["VannDy"],
    youtubeId: "zgOonh_yu8s",
    youtubeChannel: "វណ្ណដា-VannDa Official",
    about: "A collaboration with VannDy from $kull the Album.",
    tags: ["album-track", "2020", "skull", "collaboration"],
    sources: SKULL_ALBUM_SOURCES,
  },
  {
    slug: "born-this-way",
    title: "Born This Way",
    category: "album-track",
    era: "skull",
    releaseYear: 2020,
    releaseDateLabel: "June 19, 2020",
    albumSlug: "skull-the-album",
    trackNumber: 3,
    durationSeconds: 320,
    featuring: [],
    about: "Track 3 on $kull the Album.",
    tags: ["album-track", "2020", "skull"],
    sources: SKULL_ALBUM_SOURCES,
  },
  {
    slug: "hot-boy",
    title: "Hot Boy",
    category: "album-track",
    era: "skull",
    releaseYear: 2020,
    releaseDateLabel: "June 19, 2020",
    albumSlug: "skull-the-album",
    trackNumber: 4,
    durationSeconds: 227,
    featuring: [],
    youtubeId: "ACMNx6d3GPI",
    youtubeChannel: "វណ្ណដា-VannDa Official",
    about: "Track 4 on $kull the Album.",
    tags: ["album-track", "2020", "skull"],
    sources: SKULL_ALBUM_SOURCES,
  },
  {
    slug: "rampage",
    title: "Rampage",
    category: "album-track",
    era: "skull",
    releaseYear: 2020,
    releaseDateLabel: "June 19, 2020",
    albumSlug: "skull-the-album",
    trackNumber: 5,
    durationSeconds: 211,
    featuring: [],
    about: "Track 5 on $kull the Album.",
    tags: ["album-track", "2020", "skull"],
    sources: SKULL_ALBUM_SOURCES,
  },
  {
    slug: "youre-already-dead",
    title: "You're Already Dead",
    category: "album-track",
    era: "skull",
    releaseYear: 2020,
    releaseDateLabel: "June 19, 2020",
    albumSlug: "skull-the-album",
    trackNumber: 6,
    durationSeconds: 257,
    featuring: [],
    about: "Track 6 on $kull the Album.",
    tags: ["album-track", "2020", "skull"],
    sources: SKULL_ALBUM_SOURCES,
  },
  {
    slug: "life-is-a-bitch",
    title: "Life Is a Bitch",
    category: "album-track",
    era: "skull",
    releaseYear: 2020,
    releaseDateLabel: "June 19, 2020",
    albumSlug: "skull-the-album",
    trackNumber: 7,
    durationSeconds: 233,
    featuring: ["A-Gvme"],
    youtubeId: "Ydlm6oM1X4s",
    youtubeChannel: "វណ្ណដា-VannDa Official",
    about: "A collaboration with A-Gvme from $kull the Album.",
    tags: ["album-track", "2020", "skull", "collaboration"],
    sources: SKULL_ALBUM_SOURCES,
  },
  {
    slug: "back-in-the-day-remake",
    title: "Back in the Day (Remake)",
    category: "album-track",
    era: "skull",
    releaseYear: 2020,
    releaseDateLabel: "June 19, 2020",
    albumSlug: "skull-the-album",
    trackNumber: 8,
    durationSeconds: 275,
    featuring: ["La Cima Cartel"],
    about: "A remake of VannDa's 2018 independent single \"Back In The Day,\" featuring La Cima Cartel, included on $kull the Album.",
    tags: ["album-track", "2020", "skull", "collaboration"],
    sources: SKULL_ALBUM_SOURCES,
  },
  {
    slug: "j-plus-o",
    title: "J + O",
    category: "album-track",
    era: "skull",
    releaseYear: 2020,
    releaseDateLabel: "June 19, 2020",
    albumSlug: "skull-the-album",
    trackNumber: 9,
    durationSeconds: 308,
    featuring: [],
    about: "Track 9 on $kull the Album.",
    tags: ["album-track", "2020", "skull"],
    sources: SKULL_ALBUM_SOURCES,
  },
  {
    slug: "hit-the-road",
    title: "Hit the Road",
    category: "album-track",
    era: "skull",
    releaseYear: 2020,
    releaseDateLabel: "June 19, 2020",
    albumSlug: "skull-the-album",
    trackNumber: 10,
    durationSeconds: 294,
    featuring: [],
    about: "Track 10 on $kull the Album.",
    tags: ["album-track", "2020", "skull"],
    sources: SKULL_ALBUM_SOURCES,
  },
  {
    slug: "black-rose",
    title: "Black Rose",
    category: "album-track",
    era: "skull",
    releaseYear: 2020,
    releaseDateLabel: "June 19, 2020",
    albumSlug: "skull-the-album",
    trackNumber: 11,
    durationSeconds: 223,
    featuring: [],
    about: "Track 11 on $kull the Album.",
    tags: ["album-track", "2020", "skull"],
    sources: SKULL_ALBUM_SOURCES,
  },
  {
    slug: "move-on",
    title: "Move On",
    category: "album-track",
    era: "skull",
    releaseYear: 2020,
    releaseDateLabel: "June 19, 2020",
    albumSlug: "skull-the-album",
    trackNumber: 12,
    durationSeconds: 451,
    featuring: [],
    about: "Track 12 on $kull the Album.",
    tags: ["album-track", "2020", "skull"],
    sources: SKULL_ALBUM_SOURCES,
  },
  {
    slug: "no-more",
    title: "No More",
    category: "album-track",
    era: "skull",
    releaseYear: 2020,
    releaseDateLabel: "June 19, 2020",
    albumSlug: "skull-the-album",
    trackNumber: 13,
    durationSeconds: 248,
    featuring: ["Songha"],
    about: "A collaboration with Songha from $kull the Album.",
    tags: ["album-track", "2020", "skull", "collaboration"],
    sources: SKULL_ALBUM_SOURCES,
  },
  {
    slug: "2-minutes-4-you",
    title: "2minutes 4 You",
    category: "album-track",
    era: "skull",
    releaseYear: 2020,
    releaseDateLabel: "June 19, 2020",
    albumSlug: "skull-the-album",
    trackNumber: 14,
    durationSeconds: 159,
    featuring: [],
    about: "Track 14 on $kull the Album.",
    tags: ["album-track", "2020", "skull"],
    sources: SKULL_ALBUM_SOURCES,
  },
  {
    slug: "voice-memo",
    title: "Voice Memo",
    category: "album-track",
    era: "skull",
    releaseYear: 2020,
    releaseDateLabel: "June 19, 2020",
    albumSlug: "skull-the-album",
    trackNumber: 15,
    durationSeconds: 306,
    featuring: [],
    about: "Track 15 on $kull the Album.",
    tags: ["album-track", "2020", "skull"],
    sources: SKULL_ALBUM_SOURCES,
  },
  {
    slug: "nothing-to-lose",
    title: "Nothing to Lose",
    category: "album-track",
    era: "skull",
    releaseYear: 2020,
    releaseDateLabel: "June 19, 2020",
    albumSlug: "skull-the-album",
    trackNumber: 16,
    durationSeconds: 169,
    featuring: [],
    about: "Track 16 on $kull the Album.",
    tags: ["album-track", "2020", "skull"],
    sources: SKULL_ALBUM_SOURCES,
  },
  {
    slug: "mama",
    title: "MAMA",
    titleKm: "ម្តាយ",
    category: "album-track",
    era: "skull",
    releaseYear: 2020,
    releaseDateLabel: "June 19, 2020",
    albumSlug: "skull-the-album",
    trackNumber: 17,
    durationSeconds: 435,
    featuring: ["Kmeng Khmer"],
    youtubeId: "WNL3zDgWZc0",
    youtubeChannel: "វណ្ណដា-VannDa Official",
    about:
      "The penultimate track on $kull the Album, a collaboration with the group Kmeng Khmer paired with an official music video.",
    fanInterpretation:
      "Fans often point to MAMA as one of the tracks where VannDa's melodic, ballad-rooted songwriting (from his earliest 2016–2018 releases) still shows through underneath the hip-hop production.",
    tags: ["album-track", "2020", "skull", "collaboration"],
    sources: [...SKULL_ALBUM_SOURCES, WIKI],
  },
  {
    slug: "wooden-box",
    title: "Wooden Box",
    category: "album-track",
    era: "skull",
    releaseYear: 2020,
    releaseDateLabel: "June 19, 2020",
    albumSlug: "skull-the-album",
    trackNumber: 18,
    durationSeconds: 348,
    featuring: [],
    about: "The closing track of $kull the Album.",
    tags: ["album-track", "2020", "skull"],
    sources: SKULL_ALBUM_SOURCES,
  },

  // ───────────────────────── SKULL 2 (SEASON 1) (2022-07-01) ─────────────────────────
  {
    slug: "sometimes",
    title: "Sometimes",
    category: "album-track",
    era: "skull2",
    releaseYear: 2022,
    releaseDateLabel: "July 1, 2022",
    albumSlug: "skull-2-season-1",
    trackNumber: 1,
    durationSeconds: 241,
    featuring: [],
    youtubeId: "1UUfR3yIr7g",
    youtubeChannel: "វណ្ណដា-VannDa Official",
    about: "The opening track of SKULL 2 (Season 1).",
    tags: ["album-track", "2022", "skull2"],
    sources: SKULL2_SOURCES,
  },
  {
    slug: "skull-island",
    title: "Skull Island",
    category: "album-track",
    era: "skull2",
    releaseYear: 2022,
    releaseDateLabel: "July 1, 2022",
    albumSlug: "skull-2-season-1",
    trackNumber: 2,
    durationSeconds: 155,
    featuring: [],
    youtubeId: "U8zaPzS8Bqw",
    youtubeChannel: "វណ្ណដា-VannDa Official",
    about: "Track 2 on SKULL 2 (Season 1).",
    tags: ["album-track", "2022", "skull2"],
    sources: SKULL2_SOURCES,
  },
  {
    slug: "khmer-blood",
    title: "Khmer Blood",
    category: "album-track",
    era: "skull2",
    releaseYear: 2022,
    releaseDateLabel: "July 1, 2022",
    albumSlug: "skull-2-season-1",
    trackNumber: 3,
    durationSeconds: 280,
    featuring: [],
    youtubeId: "LAkKvMtlRC4",
    youtubeChannel: "វណ្ណដា-VannDa Official",
    about: "Track 3 on SKULL 2 (Season 1), with an official music video.",
    tags: ["album-track", "2022", "skull2", "cultural"],
    sources: SKULL2_SOURCES,
  },
  {
    slug: "parenthesis",
    title: "Parenthesis",
    category: "album-track",
    era: "skull2",
    releaseYear: 2022,
    releaseDateLabel: "July 1, 2022",
    albumSlug: "skull-2-season-1",
    trackNumber: 4,
    durationSeconds: 238,
    featuring: [],
    youtubeId: "IAtrZF2bdY4",
    youtubeChannel: "វណ្ណដា-VannDa Official",
    about: "Track 4 on SKULL 2 (Season 1).",
    tags: ["album-track", "2022", "skull2"],
    sources: SKULL2_SOURCES,
  },
  {
    slug: "life-is-a-game",
    title: "Life Is a Game",
    category: "album-track",
    era: "skull2",
    releaseYear: 2022,
    releaseDateLabel: "July 1, 2022",
    albumSlug: "skull-2-season-1",
    trackNumber: 5,
    durationSeconds: 216,
    featuring: [],
    youtubeId: "r2r7jctaSI0",
    youtubeChannel: "វណ្ណដា-VannDa Official",
    about: "Track 5 on SKULL 2 (Season 1).",
    tags: ["album-track", "2022", "skull2"],
    sources: SKULL2_SOURCES,
  },
  {
    slug: "day-dreamer",
    title: "Day Dreamer",
    titleKm: "សុបិនទាំងថ្ងៃ",
    category: "album-track",
    era: "skull2",
    releaseYear: 2022,
    releaseDateLabel: "July 1, 2022",
    albumSlug: "skull-2-season-1",
    trackNumber: 6,
    durationSeconds: 220,
    featuring: [],
    youtubeId: "KyrXi-q2bBY",
    youtubeChannel: "វណ្ណដា-VannDa Official",
    about: "Track 6 on SKULL 2 (Season 1), released with its own official music video.",
    tags: ["album-track", "2022", "skull2"],
    sources: SKULL2_SOURCES,
  },
  {
    slug: "night-thinker",
    title: "Night Thinker",
    category: "album-track",
    era: "skull2",
    releaseYear: 2022,
    releaseDateLabel: "July 1, 2022",
    albumSlug: "skull-2-season-1",
    trackNumber: 7,
    durationSeconds: 209,
    featuring: [],
    youtubeId: "vK_oavImOwc",
    youtubeChannel: "វណ្ណដា-VannDa Official",
    about: "Track 7 on SKULL 2 (Season 1).",
    tags: ["album-track", "2022", "skull2"],
    sources: SKULL2_SOURCES,
  },
  {
    slug: "hows-it-taste",
    title: "How's It Taste?",
    titleKm: "រសជាតិយ៉ាងម៉េច?",
    category: "album-track",
    era: "skull2",
    releaseYear: 2022,
    releaseDateLabel: "July 1, 2022",
    albumSlug: "skull-2-season-1",
    trackNumber: 8,
    durationSeconds: 248,
    featuring: [],
    youtubeId: "Q9-KIFNSFMs",
    youtubeChannel: "វណ្ណដា-VannDa Official",
    about: "Track 8 on SKULL 2 (Season 1), with an official music video.",
    tags: ["album-track", "2022", "skull2"],
    sources: SKULL2_SOURCES,
  },
  {
    slug: "bok-kalo",
    title: "Bok Kalo",
    category: "album-track",
    era: "skull2",
    releaseYear: 2022,
    releaseDateLabel: "July 1, 2022",
    albumSlug: "skull-2-season-1",
    trackNumber: 9,
    durationSeconds: 201,
    featuring: [],
    youtubeId: "18mgN64R_FE",
    youtubeChannel: "វណ្ណដា-VannDa Official",
    about: "Track 9 on SKULL 2 (Season 1), with an official music video.",
    tags: ["album-track", "2022", "skull2"],
    sources: SKULL2_SOURCES,
  },
  {
    slug: "daddy-da",
    title: "Daddy Da",
    category: "album-track",
    era: "skull2",
    releaseYear: 2022,
    releaseDateLabel: "July 1, 2022",
    albumSlug: "skull-2-season-1",
    trackNumber: 10,
    durationSeconds: 224,
    featuring: [],
    youtubeId: "wVPmbqc0uDY",
    youtubeChannel: "វណ្ណដា-VannDa Official",
    about: "Track 10 on SKULL 2 (Season 1), released with a joint official music video alongside \"King.\"",
    tags: ["album-track", "2022", "skull2"],
    sources: SKULL2_SOURCES,
  },
  {
    slug: "catch-me-if-you-can",
    title: "Catch Me If You Can",
    category: "album-track",
    era: "skull2",
    releaseYear: 2022,
    releaseDateLabel: "July 1, 2022",
    albumSlug: "skull-2-season-1",
    trackNumber: 11,
    durationSeconds: 342,
    featuring: [],
    youtubeId: "H4vQNl4mVTI",
    youtubeChannel: "វណ្ណដា-VannDa Official",
    about: "Track 11 on SKULL 2 (Season 1), with an official music video.",
    tags: ["album-track", "2022", "skull2"],
    sources: SKULL2_SOURCES,
  },
  {
    slug: "young-man",
    title: "Young Man",
    category: "album-track",
    era: "skull2",
    releaseYear: 2022,
    releaseDateLabel: "July 1, 2022",
    albumSlug: "skull-2-season-1",
    trackNumber: 12,
    durationSeconds: 246,
    featuring: ["OG Bobby"],
    youtubeId: "nHXLfMeNoLA",
    youtubeChannel: "វណ្ណដា-VannDa Official",
    about: "VannDa's first collaboration with OG Bobby, track 12 on SKULL 2 (Season 1).",
    tags: ["album-track", "2022", "skull2", "collaboration"],
    sources: SKULL2_SOURCES,
  },
  {
    slug: "elevator",
    title: "Elevator",
    category: "album-track",
    era: "skull2",
    releaseYear: 2022,
    releaseDateLabel: "July 1, 2022",
    albumSlug: "skull-2-season-1",
    trackNumber: 13,
    durationSeconds: 151,
    featuring: [],
    youtubeId: "cKaDeDqXOkA",
    youtubeChannel: "វណ្ណដា-VannDa Official",
    about: "Track 13 on SKULL 2 (Season 1).",
    tags: ["album-track", "2022", "skull2"],
    sources: SKULL2_SOURCES,
  },
  {
    slug: "king",
    title: "King",
    category: "album-track",
    era: "skull2",
    releaseYear: 2022,
    releaseDateLabel: "July 1, 2022",
    albumSlug: "skull-2-season-1",
    trackNumber: 14,
    durationSeconds: 153,
    featuring: [],
    youtubeId: "wVPmbqc0uDY",
    youtubeChannel: "វណ្ណដា-VannDa Official",
    about: "Track 14 on SKULL 2 (Season 1), released with a joint official music video alongside \"Daddy Da.\"",
    tags: ["album-track", "2022", "skull2"],
    sources: SKULL2_SOURCES,
  },
  {
    slug: "coda",
    title: "C.O.D.A",
    category: "album-track",
    era: "skull2",
    releaseYear: 2022,
    releaseDateLabel: "July 1, 2022",
    albumSlug: "skull-2-season-1",
    trackNumber: 15,
    durationSeconds: 260,
    featuring: [],
    youtubeId: "VYLM-vpdQ1A",
    youtubeChannel: "វណ្ណដា-VannDa Official",
    about:
      "\"C.O.D.A\" (Culture Of Devoted Aspiration) closes SKULL 2 (Season 1), VannDa's sophomore full-length album.",
    tags: ["album-track", "2022", "skull2"],
    sources: SKULL2_SOURCES,
  },

  // ───────────────────────── TREYVISAI I: The Search for Light (2025-03-14) ─────────────────────────
  {
    slug: "here-and-there",
    title: "Here & There",
    category: "album-track",
    era: "treyvisai",
    releaseYear: 2025,
    releaseDateLabel: "March 14, 2025",
    albumSlug: "treyvisai-i",
    trackNumber: 1,
    featuring: [],
    youtubeId: "a1i-hZsG0vo",
    youtubeChannel: "វណ្ណដា-VannDa Official",
    about: "The opening track of TREYVISAI I: The Search for Light.",
    tags: ["album-track", "2025", "treyvisai"],
    sources: TREYVISAI1_SOURCES,
  },
  {
    slug: "out-of-my-mind",
    title: "Out Of My Mind",
    category: "album-track",
    era: "treyvisai",
    releaseYear: 2025,
    releaseDateLabel: "March 14, 2025",
    albumSlug: "treyvisai-i",
    trackNumber: 2,
    featuring: [],
    youtubeId: "aSOuRMyxdNA",
    youtubeChannel: "វណ្ណដា-VannDa Official",
    about: "A high-energy track from TREYVISAI I: The Search for Light.",
    tags: ["album-track", "2025", "treyvisai"],
    sources: TREYVISAI1_SOURCES,
  },
  {
    slug: "me-my-flow-and-i",
    title: "Me, My Flow, & I",
    category: "album-track",
    era: "treyvisai",
    releaseYear: 2025,
    releaseDateLabel: "March 14, 2025",
    albumSlug: "treyvisai-i",
    trackNumber: 3,
    featuring: [],
    youtubeId: "qqJGcAsMaKM",
    youtubeChannel: "វណ្ណដា-VannDa Official",
    about: "Track 3 on TREYVISAI I: The Search for Light.",
    tags: ["album-track", "2025", "treyvisai"],
    sources: TREYVISAI1_SOURCES,
  },
  {
    slug: "u-know-u-know",
    title: "U Know U Know",
    category: "album-track",
    era: "treyvisai",
    releaseYear: 2025,
    releaseDateLabel: "March 14, 2025",
    albumSlug: "treyvisai-i",
    trackNumber: 4,
    featuring: [],
    youtubeId: "3mmUl2112Cw",
    youtubeChannel: "វណ្ណដា-VannDa Official",
    about: "Track 4 on TREYVISAI I: The Search for Light, with an official video.",
    tags: ["album-track", "2025", "treyvisai"],
    sources: TREYVISAI1_SOURCES,
  },
  {
    slug: "fishing",
    title: "Fishing",
    category: "album-track",
    era: "treyvisai",
    releaseYear: 2025,
    releaseDateLabel: "March 14, 2025",
    albumSlug: "treyvisai-i",
    trackNumber: 5,
    featuring: [],
    youtubeId: "R5Lx2xCwsJQ",
    youtubeChannel: "វណ្ណដា-VannDa Official",
    about: "Track 5 on TREYVISAI I: The Search for Light.",
    tags: ["album-track", "2025", "treyvisai"],
    sources: TREYVISAI1_SOURCES,
  },
  {
    slug: "business-class",
    title: "Business Class",
    category: "album-track",
    era: "treyvisai",
    releaseYear: 2025,
    releaseDateLabel: "March 14, 2025",
    albumSlug: "treyvisai-i",
    trackNumber: 6,
    featuring: [],
    youtubeId: "_9ELMrLwkCY",
    youtubeChannel: "វណ្ណដា-VannDa Official",
    about: "Track 6 on TREYVISAI I: The Search for Light, with an official video.",
    tags: ["album-track", "2025", "treyvisai"],
    sources: TREYVISAI1_SOURCES,
  },
  {
    slug: "smoke-up",
    title: "Smoke Up",
    category: "album-track",
    era: "treyvisai",
    releaseYear: 2025,
    releaseDateLabel: "March 14, 2025",
    albumSlug: "treyvisai-i",
    trackNumber: 7,
    featuring: ["YOUNGOHM"],
    spotifyUrl: "https://open.spotify.com/track/2fksVb2QNDPHsq0aCnYTTu",
    about:
      "The lead single of TREYVISAI I: The Search for Light, joining VannDa with Thai rap icon YOUNGOHM — a marquee moment for Southeast Asian hip-hop.",
    tags: ["album-track", "2025", "treyvisai", "collaboration", "regional"],
    sources: [
      ...TREYVISAI1_SOURCES,
      {
        label: "Bandwagon Asia — Smoke Up",
        url: "https://www.bandwagon.asia/articles/vannda-drops-1st-of-ep-trilogy",
      },
    ],
  },
  {
    slug: "ptsd",
    title: "PTSD",
    category: "album-track",
    era: "treyvisai",
    releaseYear: 2025,
    releaseDateLabel: "March 14, 2025",
    albumSlug: "treyvisai-i",
    trackNumber: 8,
    featuring: [],
    youtubeId: "frGzTSAJhgU",
    youtubeChannel: "វណ្ណដា-VannDa Official",
    about: "The closing track of TREYVISAI I: The Search for Light.",
    tags: ["album-track", "2025", "treyvisai"],
    sources: TREYVISAI1_SOURCES,
  },

  // ───────────────────────── TREYVISAI II: Burn Like the Sun (2025-03-21) ─────────────────────────
  {
    slug: "burn",
    title: "Burn",
    category: "album-track",
    era: "treyvisai",
    releaseYear: 2025,
    releaseDateLabel: "March 21, 2025",
    albumSlug: "treyvisai-ii",
    trackNumber: 1,
    featuring: [],
    youtubeId: "HBet3JZ5AnM",
    youtubeChannel: "វណ្ណដា-VannDa Official",
    about: "The opening track of TREYVISAI II: Burn Like the Sun.",
    tags: ["album-track", "2025", "treyvisai"],
    sources: TREYVISAI2_SOURCES,
  },
  {
    slug: "no-disrespect",
    title: "No Disrespect",
    category: "album-track",
    era: "treyvisai",
    releaseYear: 2025,
    releaseDateLabel: "March 21, 2025",
    albumSlug: "treyvisai-ii",
    trackNumber: 2,
    featuring: [],
    youtubeId: "7t0qrQ0o42M",
    youtubeChannel: "វណ្ណដា-VannDa Official",
    about:
      "The lead single from TREYVISAI II: Burn Like the Sun, the second installment of VannDa's 2025 mini-album trilogy — its Khmer title translates to \"the compass.\"",
    tags: ["album-track", "2025", "treyvisai"],
    sources: TREYVISAI2_SOURCES,
  },
  {
    slug: "dangerous",
    title: "Dangerous",
    category: "album-track",
    era: "treyvisai",
    releaseYear: 2025,
    releaseDateLabel: "March 21, 2025",
    albumSlug: "treyvisai-ii",
    trackNumber: 3,
    featuring: [],
    youtubeId: "_GCacrYO-Xo",
    youtubeChannel: "វណ្ណដា-VannDa Official",
    about: "Track 3 on TREYVISAI II: Burn Like the Sun, produced by illmind.",
    tags: ["album-track", "2025", "treyvisai"],
    sources: TREYVISAI2_SOURCES,
  },
  {
    slug: "broken-compass",
    title: "Broken Compass",
    category: "album-track",
    era: "treyvisai",
    releaseYear: 2025,
    releaseDateLabel: "March 21, 2025",
    albumSlug: "treyvisai-ii",
    trackNumber: 4,
    featuring: [],
    youtubeId: "0fHJrnuWDa0",
    youtubeChannel: "វណ្ណដា-VannDa Official",
    about: "Track 4 on TREYVISAI II: Burn Like the Sun.",
    tags: ["album-track", "2025", "treyvisai"],
    sources: TREYVISAI2_SOURCES,
  },
  {
    slug: "love-sick-blue",
    title: "Love Sick Blue",
    category: "album-track",
    era: "treyvisai",
    releaseYear: 2025,
    releaseDateLabel: "March 21, 2025",
    albumSlug: "treyvisai-ii",
    trackNumber: 5,
    featuring: ["Thinlamphone"],
    youtubeId: "wWfY_dLNoNI",
    youtubeChannel: "វណ្ណដា-VannDa Official",
    about: "A cross-border collaboration with Laotian artist Thinlamphone on TREYVISAI II: Burn Like the Sun.",
    tags: ["album-track", "2025", "treyvisai", "collaboration", "regional"],
    sources: TREYVISAI2_SOURCES,
  },
  {
    slug: "zerd-zerd",
    title: "Zerd Zerd",
    category: "album-track",
    era: "treyvisai",
    releaseYear: 2025,
    releaseDateLabel: "March 21, 2025",
    albumSlug: "treyvisai-ii",
    trackNumber: 6,
    featuring: ["Norith"],
    youtubeId: "S-UL2pa4BGs",
    youtubeChannel: "វណ្ណដា-VannDa Official",
    about: "A collaboration with Cambodian artist Norith on TREYVISAI II: Burn Like the Sun.",
    tags: ["album-track", "2025", "treyvisai", "collaboration"],
    sources: TREYVISAI2_SOURCES,
  },
  {
    slug: "a-song-for-you",
    title: "A Song For You",
    titleKm: "ចម្រៀងជូន Ex",
    category: "album-track",
    era: "treyvisai",
    releaseYear: 2025,
    releaseDateLabel: "March 21, 2025",
    albumSlug: "treyvisai-ii",
    trackNumber: 7,
    featuring: [],
    youtubeId: "k15Llu-dwmg",
    youtubeChannel: "វណ្ណដា-VannDa Official",
    about:
      "The closing track of TREYVISAI II: Burn Like the Sun, part of VannDa's recurring \"ចម្រៀងជូន Ex\" (Song For My Ex) series that traces back to his earliest independent releases.",
    tags: ["album-track", "2025", "treyvisai"],
    sources: TREYVISAI2_SOURCES,
  },

  // ───────────────────────── TREYVISAI III: Return to Sovannaphum (2025-05-15) ─────────────────────────
  {
    slug: "lakhon-bassac",
    title: "Lakhon Bassac",
    category: "album-track",
    era: "treyvisai",
    releaseYear: 2025,
    releaseDateLabel: "May 15, 2025",
    albumSlug: "treyvisai-iii",
    trackNumber: 1,
    featuring: [],
    youtubeId: "wCxWft58vHM",
    youtubeChannel: "វណ្ណដា-VannDa Official",
    about:
      "The opening track of TREYVISAI III: Return to Sovannaphum, named for Lakhon Bassac, a traditional Cambodian theatrical folk-opera style.",
    tags: ["album-track", "2025", "treyvisai", "cultural"],
    sources: TREYVISAI3_SOURCES,
  },
  {
    slug: "360",
    title: "360",
    category: "album-track",
    era: "treyvisai",
    releaseYear: 2025,
    releaseDateLabel: "May 15, 2025",
    albumSlug: "treyvisai-iii",
    trackNumber: 2,
    featuring: [],
    youtubeId: "VangtodgL0Y",
    youtubeChannel: "វណ្ណដា-VannDa Official",
    about: "Track 2 on TREYVISAI III: Return to Sovannaphum, produced by Vanthan.",
    tags: ["album-track", "2025", "treyvisai"],
    sources: TREYVISAI3_SOURCES,
  },
  {
    slug: "the-word-of-vannda",
    title: "The Word of VannDa",
    category: "album-track",
    era: "treyvisai",
    releaseYear: 2025,
    releaseDateLabel: "May 15, 2025",
    albumSlug: "treyvisai-iii",
    trackNumber: 3,
    featuring: [],
    youtubeId: "B6DoGmPij3g",
    youtubeChannel: "វណ្ណដា-VannDa Official",
    about: "An interlude track on TREYVISAI III: Return to Sovannaphum.",
    tags: ["album-track", "2025", "treyvisai", "interlude"],
    sources: TREYVISAI3_SOURCES,
  },
  {
    slug: "ah-thma",
    title: "Ah Thma",
    titleKm: "អាត្មា",
    category: "album-track",
    era: "treyvisai",
    releaseYear: 2025,
    releaseDateLabel: "May 15, 2025",
    albumSlug: "treyvisai-iii",
    trackNumber: 4,
    featuring: [],
    youtubeId: "xWDlDo-LT1I",
    youtubeChannel: "វណ្ណដា-VannDa Official",
    about: "Track 4 on TREYVISAI III: Return to Sovannaphum.",
    tags: ["album-track", "2025", "treyvisai"],
    sources: TREYVISAI3_SOURCES,
  },
  {
    slug: "metta",
    title: "Metta",
    category: "album-track",
    era: "treyvisai",
    releaseYear: 2025,
    releaseDateLabel: "May 15, 2025",
    albumSlug: "treyvisai-iii",
    trackNumber: 5,
    featuring: [],
    youtubeId: "G7FsNyYb92U",
    youtubeChannel: "វណ្ណដា-VannDa Official",
    about: "Track 5 on TREYVISAI III: Return to Sovannaphum, its title referencing the Buddhist concept of loving-kindness.",
    tags: ["album-track", "2025", "treyvisai", "cultural"],
    sources: TREYVISAI3_SOURCES,
  },
  {
    slug: "good-old-days",
    title: "Good Old Days",
    category: "album-track",
    era: "treyvisai",
    releaseYear: 2025,
    releaseDateLabel: "May 15, 2025",
    albumSlug: "treyvisai-iii",
    trackNumber: 6,
    featuring: [],
    youtubeId: "3LJv4NnRrKU",
    youtubeChannel: "វណ្ណដា-VannDa Official",
    about: "Track 6 on TREYVISAI III: Return to Sovannaphum.",
    tags: ["album-track", "2025", "treyvisai"],
    sources: TREYVISAI3_SOURCES,
  },
  {
    slug: "make-your-luck",
    title: "Make Your Luck",
    category: "album-track",
    era: "treyvisai",
    releaseYear: 2025,
    releaseDateLabel: "May 15, 2025",
    albumSlug: "treyvisai-iii",
    trackNumber: 7,
    featuring: ["Vanthan"],
    youtubeId: "zKkbQiaSY0g",
    youtubeChannel: "វណ្ណដា-VannDa Official",
    about: "A collaboration with labelmate Vanthan on TREYVISAI III: Return to Sovannaphum.",
    tags: ["album-track", "2025", "treyvisai", "collaboration", "baramey"],
    sources: TREYVISAI3_SOURCES,
  },
  {
    slug: "golden-land",
    title: "Golden Land",
    titleKm: "សុវណ្ណភូមិ",
    category: "album-track",
    era: "treyvisai",
    releaseYear: 2025,
    releaseDateLabel: "May 15, 2025",
    albumSlug: "treyvisai-iii",
    trackNumber: 8,
    featuring: [],
    youtubeId: "jFVfxBQjMFU",
    youtubeChannel: "វណ្ណដា-VannDa Official",
    about:
      "The centerpiece of TREYVISAI III: Return to Sovannaphum, released with a cinematic music video woven together with \"Varman Blood.\"",
    tags: ["album-track", "2025", "treyvisai", "cultural"],
    sources: TREYVISAI3_SOURCES,
  },
  {
    slug: "varman-blood",
    title: "Varman Blood",
    category: "album-track",
    era: "treyvisai",
    releaseYear: 2025,
    releaseDateLabel: "May 15, 2025",
    albumSlug: "treyvisai-iii",
    trackNumber: 9,
    featuring: [],
    youtubeId: "_uM-cgPcZ3E",
    youtubeChannel: "វណ្ណដា-VannDa Official",
    about: "Track 9 on TREYVISAI III: Return to Sovannaphum, thematically woven together with \"Golden Land.\"",
    tags: ["album-track", "2025", "treyvisai", "cultural"],
    sources: TREYVISAI3_SOURCES,
  },
  {
    slug: "dont-worry",
    title: "Don't Worry",
    category: "album-track",
    era: "treyvisai",
    releaseYear: 2025,
    releaseDateLabel: "May 15, 2025",
    albumSlug: "treyvisai-iii",
    trackNumber: 10,
    featuring: [],
    youtubeId: "LwMh58G_9tI",
    youtubeChannel: "វណ្ណដា-VannDa Official",
    about:
      "The closing track of TREYVISAI III: Return to Sovannaphum, bringing VannDa's three-part 2025 mini-album trilogy to a close.",
    tags: ["album-track", "2025", "treyvisai"],
    sources: TREYVISAI3_SOURCES,
  },

  // ───────────────────────── Standalone singles ─────────────────────────
  {
    slug: "time-to-rise",
    title: "Time To Rise",
    category: "single",
    era: "breakthrough",
    releaseYear: 2021,
    releaseDateLabel: "2021",
    featuring: ["Master Kong Nay"],
    youtubeId: "rvje5oblrLw",
    youtubeChannel: "វណ្ណដា-VannDa Official",
    spotifyUrl: "https://open.spotify.com/track/7DJjwQuj6XpJSxxY8c6O8B",
    about:
      "VannDa's breakthrough single, built around a collaboration with chrieng chapei master Kong Nay — one of the few great masters of the genre to have survived the Khmer Rouge era. Originally created for a Cellcard marketing campaign, the music video was filmed at the National Museum of Cambodia and blends traditional chapei dang veng playing with modern hip-hop. In October 2022 it became the first music video by a Cambodian artist to pass 100 million YouTube views.",
    fanInterpretation:
      "For many Cambodian fans, this is the song that made Khmer hip-hop feel like it belonged on a world stage without leaving its own culture behind — Kong Nay's verses read as a literal passing of the torch to a new generation.",
    tags: ["single", "2021", "breakthrough", "collaboration", "traditional"],
    sources: [WIKI, BARAMEY],
  },
  {
    slug: "6-years-in-the-game",
    title: "6 Years In The Game",
    category: "single",
    era: "global",
    releaseYear: 2024,
    releaseDateLabel: "2024",
    featuring: ["Awich"],
    youtubeId: "UAoI1SyWprI",
    youtubeChannel: "វណ្ណដា-VannDa Official",
    about:
      "A collaboration with Japanese rapper Awich, marking six years since VannDa's first hip-hop releases and part of his growing run of international collaborations.",
    tags: ["single", "2024", "collaboration", "international"],
    sources: [WIKI],
  },
  {
    slug: "skull-if-i-die",
    title: "Skull (If I Die)",
    category: "single",
    era: "skull2",
    releaseYear: 2021,
    releaseDateLabel: "2021",
    featuring: [],
    youtubeId: "uylsiQUKEdg",
    youtubeChannel: "វណ្ណដា-VannDa Official",
    about: "A standalone single released between $kull the Album and SKULL 2 (Season 1).",
    tags: ["single", "2021"],
    sources: [{ label: "YouTube — VannDa Official", url: "https://www.youtube.com/watch?v=uylsiQUKEdg" }],
  },
  {
    slug: "hanuman-nights",
    title: "Hanuman Nights",
    category: "single",
    era: "baramey-crew",
    releaseYear: 2023,
    releaseDateLabel: "April 7, 2023",
    durationSeconds: 259,
    featuring: [],
    youtubeId: "smOwVy_iu3E",
    youtubeChannel: "វណ្ណដា-VannDa Official",
    spotifyUrl: "https://open.spotify.com/track/2nCcI4UtqpethLV3TdiGlp",
    appleMusicUrl: "https://music.apple.com/in/album/hanuman-nights-single/1800383757",
    about: "A standalone single released via Baramey Production / EMPIRE.",
    tags: ["single", "2023", "cultural"],
    sources: [
      { label: "Apple Music — Hanuman Nights", url: "https://music.apple.com/in/album/hanuman-nights-single/1800383757" },
    ],
  },
  {
    slug: "sangkran-magic",
    title: "Sangkran Magic",
    titleKm: "សង្រ្កាន្តស្គាល់ស្នេហ៍",
    category: "single",
    era: "baramey-crew",
    releaseYear: 2023,
    releaseDateLabel: "2023",
    featuring: [],
    youtubeId: "Cpo3DmbdCxs",
    youtubeChannel: "វណ្ណដា-VannDa Official",
    about: "A single released around Khmer New Year (Sangkran), released on VannDa's official channel.",
    tags: ["single", "2023", "cultural"],
    sources: [{ label: "YouTube — VannDa Official", url: "https://www.youtube.com/watch?v=Cpo3DmbdCxs" }],
  },
  {
    slug: "baby-mama",
    title: "Baby Mama",
    category: "single",
    era: "skull2",
    releaseYear: 2022,
    releaseDateLabel: "2022",
    featuring: [],
    youtubeId: "Jbt5dRYFOPo",
    youtubeChannel: "វណ្ណដា-VannDa Official",
    about: "A single released on VannDa's official channel during the SKULL 2 era.",
    tags: ["single", "2022"],
    sources: [{ label: "YouTube — VannDa Official", url: "https://www.youtube.com/watch?v=Jbt5dRYFOPo" }],
  },
  {
    slug: "bad-lil-boo",
    title: "Bad Lil Boo",
    titleKm: "អាមុំបងអើយ",
    category: "single",
    era: "global",
    releaseYear: 2024,
    releaseDateLabel: "November 12, 2024",
    featuring: [],
    youtubeId: "dXITrblyQCs",
    youtubeChannel: "វណ្ណដា-VannDa Official",
    appleMusicUrl: "https://music.apple.com/us/album/bad-lil-boo-single/1800383911",
    about: "A standalone single released in late 2024.",
    tags: ["single", "2024"],
    sources: [{ label: "Apple Music — Bad Lil Boo", url: "https://music.apple.com/us/album/bad-lil-boo-single/1800383911" }],
  },
  {
    slug: "nobody-but-us",
    title: "Nobody But Us",
    category: "single",
    era: "global",
    releaseYear: 2024,
    releaseDateLabel: "2024",
    featuring: [],
    youtubeId: "w7cH42I7v80",
    youtubeChannel: "វណ្ណដា-VannDa Official",
    about: "A standalone single released in 2024, with an official lyric video.",
    tags: ["single", "2024"],
    sources: [{ label: "YouTube — VannDa Official", url: "https://www.youtube.com/watch?v=w7cH42I7v80" }],
  },
  {
    slug: "neon-light",
    title: "Neon Light",
    category: "single",
    era: "current",
    releaseYear: 2026,
    releaseDateLabel: "January 22, 2026",
    featuring: [],
    youtubeId: "uv4JKlL1o84",
    youtubeChannel: "វណ្ណដា-VannDa Official",
    appleMusicUrl: "https://music.apple.com/gb/song/neon-light/1870831008",
    about: "A single released on VannDa's birthday, produced and written by VannDa, mixed and mastered by Vito.",
    tags: ["single", "2026", "current"],
    sources: [
      { label: "Apple Music — Neon Light", url: "https://music.apple.com/gb/song/neon-light/1870831008" },
      { label: "YouTube — VannDa Official", url: "https://www.youtube.com/watch?v=uv4JKlL1o84" },
    ],
  },
  {
    slug: "new-cut",
    title: "New Cut",
    category: "single",
    era: "current",
    releaseYear: 2026,
    releaseDateLabel: "February 25, 2026",
    featuring: [],
    youtubeId: "_j4_HzqV6ak",
    youtubeChannel: "វណ្ណដា-VannDa Official",
    spotifyUrl: "https://open.spotify.com/album/0IOZtY3nT3pFhhNKV5fuar",
    about: "A single released in early 2026.",
    tags: ["single", "2026", "current"],
    sources: [{ label: "Spotify — New Cut", url: "https://open.spotify.com/album/0IOZtY3nT3pFhhNKV5fuar" }],
  },
  {
    slug: "back-home",
    title: "Back Home",
    titleKm: "ជួបជុំ",
    category: "single",
    era: "current",
    releaseYear: 2026,
    releaseDateLabel: "April 10, 2026",
    featuring: [],
    youtubeId: "dryShmzXrgo",
    youtubeChannel: "វណ្ណដា-VannDa Official",
    appleMusicUrl: "https://music.apple.com/us/album/back-home-single/1891126660",
    about: "A single released in spring 2026.",
    tags: ["single", "2026", "current"],
    sources: [{ label: "Apple Music — Back Home", url: "https://music.apple.com/us/album/back-home-single/1891126660" }],
  },
  {
    slug: "do-you",
    title: "Do You",
    category: "single",
    era: "current",
    releaseYear: 2026,
    releaseDateLabel: "August 10, 2026",
    featuring: [],
    youtubeId: "NOSnCDUoOio",
    youtubeChannel: "វណ្ណដា-VannDa Official",
    about: "VannDa's most recent single as of this writing.",
    tags: ["single", "2026", "current"],
    sources: [{ label: "Amazon Music — Do You", url: "https://music.amazon.com/artists/B07VHF9NZ7/vannda" }],
  },
  {
    slug: "hero-2-villain",
    title: "Hero 2 Villain",
    category: "single",
    era: "current",
    releaseYear: 2026,
    releaseDateLabel: "August 2026",
    featuring: [],
    youtubeId: "tTs0kJ9E8NY",
    youtubeChannel: "វណ្ណដា-VannDa Official",
    about:
      "A single released alongside \"Blue Story\" and \"Do You\" in a small batch of August 2026 releases; the exact release day is not independently confirmed.",
    tags: ["single", "2026", "current"],
    sources: [
      {
        label: "Facebook — Baramey Official",
        url: "https://www.facebook.com/barameyofficial/posts/vannda-hero-2-villain-blue-story-do-you-official-video1-hero-2-villainmusic-cred/1592978672206931/",
      },
    ],
  },
  {
    slug: "blue-story",
    title: "Blue Story",
    category: "single",
    era: "current",
    releaseYear: 2026,
    releaseDateLabel: "August 2026",
    featuring: [],
    youtubeId: "0jSgcE-sxeo",
    youtubeChannel: "វណ្ណដា-VannDa Official",
    about:
      "A single released alongside \"Hero 2 Villain\" and \"Do You\" in a small batch of August 2026 releases; the exact release day is not independently confirmed.",
    tags: ["single", "2026", "current"],
    sources: [
      {
        label: "Facebook — Baramey Official",
        url: "https://www.facebook.com/barameyofficial/posts/vannda-hero-2-villain-blue-story-do-you-official-video1-hero-2-villainmusic-cred/1592978672206931/",
      },
    ],
  },

  // ───────────────────────── Collaborations (joint billing) ─────────────────────────
  {
    slug: "monsoon",
    title: "Monsoon",
    category: "collaboration",
    era: "breakthrough",
    releaseYear: 2021,
    releaseDateLabel: "2021",
    featuring: ["Songha"],
    youtubeId: "yMx-jKePx98",
    youtubeChannel: "វណ្ណដា-VannDa Official",
    about: "A collaboration with singer Songha released on VannDa's official channel during his 2021 breakthrough run.",
    tags: ["collaboration", "2021"],
    sources: [WIKI],
  },
  {
    slug: "run-the-town",
    title: "Run The Town",
    category: "collaboration",
    era: "skull2",
    releaseYear: 2022,
    releaseDateLabel: "2022",
    featuring: ["F.HERO", "1MILL", "Sprite"],
    youtubeId: "UwE8RPbPmrI",
    youtubeChannel: "វណ្ណដា-VannDa Official",
    about:
      "A regional crossover single joining VannDa with Thai artists F.HERO and 1MILL, produced by High Cloud Entertainment.",
    tags: ["collaboration", "2022", "regional"],
    sources: [WIKI],
  },
  {
    slug: "khmer-gentlemen",
    title: "Khmer Gentlemen",
    titleKm: "កម្លោះស្រុកខ្មែរ",
    category: "collaboration",
    era: "baramey-crew",
    releaseYear: 2023,
    releaseDateLabel: "2023",
    featuring: ["Vanthan"],
    youtubeId: "fJuJ6GW0UEk",
    youtubeChannel: "Vanthan - វណ្ណថាន Official",
    about: "A collaboration with fellow Baramey Production artist Vanthan, released on Vanthan's official channel.",
    tags: ["collaboration", "2023", "baramey"],
    sources: [WIKI],
  },
  {
    slug: "legacy",
    title: "Legacy",
    titleKm: "ចងចាំសាវតារ",
    category: "collaboration",
    era: "baramey-crew",
    releaseYear: 2023,
    releaseDateLabel: "2023",
    featuring: ["Baramey Crew"],
    youtubeId: "StNAenr4rVY",
    youtubeChannel: "Baramey Official",
    about: "A posse cut released under the Baramey Crew banner, bringing together artists from the Baramey Production roster.",
    tags: ["collaboration", "2023", "baramey"],
    sources: [WIKI],
  },
  {
    slug: "asian-state-of-mind",
    title: "Asian State Of Mind",
    category: "collaboration",
    era: "global",
    releaseYear: 2025,
    releaseDateLabel: "2025",
    featuring: ["Awich", "Jay Park", "KR$NA", "Masiwei"],
    youtubeId: "QRnO04UwnM0",
    youtubeChannel: "Awich",
    about:
      "A pan-Asian posse cut produced by Diego Ave, bringing together Awich (Japan), Jay Park (Korea/USA), KR$NA (India), Masiwei (China), and VannDa (Cambodia) on one track.",
    tags: ["collaboration", "2025", "international"],
    sources: [WIKI],
  },
  {
    slug: "fifty-fifty",
    title: "50-50",
    titleKm: "៥០ ៥០",
    category: "collaboration",
    era: "current",
    releaseYear: 2025,
    releaseDateLabel: "April 14, 2025",
    featuring: ["Vanthan"],
    youtubeId: "aRa1LdjgWbs",
    youtubeChannel: "វណ្ណដា-VannDa Official",
    spotifyUrl: "https://open.spotify.com/track/49EswiEGkPPutrtdELxzrb",
    appleMusicUrl: "https://music.apple.com/ug/album/50-50-single/1808532805",
    about:
      "\"VannDa x Vanthan\" — released for Khmer New Year 2025, a music video directed by Lim Heng Will exploring love caught between hesitation and affection.",
    tags: ["collaboration", "2025", "baramey", "cultural"],
    sources: [
      { label: "Deezer — 50-50", url: "https://www.deezer.com/en/album/742527051" },
      { label: "Apple Music — 50-50", url: "https://music.apple.com/ug/album/50-50-single/1808532805" },
    ],
  },
  {
    slug: "decade-of-love",
    title: "Decade of Love",
    category: "collaboration",
    era: "current",
    releaseYear: 2026,
    releaseDateLabel: "February 12, 2026",
    durationSeconds: 213,
    featuring: ["Norith"],
    youtubeId: "yUscz-A6E0s",
    youtubeChannel: "វណ្ណដា-VannDa Official",
    appleMusicUrl: "https://music.apple.com/us/song/decade-of-love/1874452089",
    about: "\"Norith & VannDa\" — a joint single released in early 2026.",
    tags: ["collaboration", "2026", "current"],
    sources: [
      { label: "Apple Music — Decade of Love", url: "https://music.apple.com/in/album/decade-of-love-single/1874452080" },
    ],
  },

  // ───────────────────────── Featured appearances (other artist primary) ─────────────────────────
  {
    slug: "time",
    title: "Time",
    category: "featured",
    era: "breakthrough",
    releaseYear: 2021,
    releaseDateLabel: "2021",
    primaryArtist: "Sophia Kao",
    featuring: [],
    youtubeId: "_1sdvk_8bYk",
    youtubeChannel: "Sophia Kao",
    about: "A collaboration with singer-songwriter Sophia Kao, released on her channel the same breakthrough year as Time To Rise.",
    tags: ["featured", "2021"],
    sources: [WIKI],
  },
  {
    slug: "player-tempo-tris",
    title: "Player",
    titleKm: "អ្នកលេង",
    category: "featured",
    era: "independent",
    releaseYear: 2018,
    releaseDateLabel: "2018",
    primaryArtist: "Tempo Tris",
    featuring: ["Rawyer", "Snooga", "Reezy"],
    about: "An early appearance on Tempo Tris's \"Player,\" alongside Rawyer, Snooga, and Reezy — one of VannDa's pre-Baramey features.",
    tags: ["featured", "2018", "independent"],
    sources: [{ label: "Apple Music — Tempo Tris", url: "https://music.apple.com/us/artist/tempo-tris/1533607395" }],
  },
  {
    slug: "kwan-mekh-beok-thngai",
    title: "មេឃបើកថ្ងៃ",
    category: "featured",
    era: "global",
    releaseYear: 2024,
    releaseDateLabel: "2024",
    primaryArtist: "Kwan",
    featuring: [],
    youtubeId: "Yvw5LaQEcm0",
    youtubeChannel: "KWAN",
    spotifyUrl: "https://open.spotify.com/track/6HWbL3uNRzkisSZoyqydaT",
    appleMusicUrl: "https://music.apple.com/kh/song/%E1%9E%98-%E1%9E%83%E1%9E%94-%E1%9E%80%E1%9E%90-%E1%9E%84-feat-vannda/1727115109",
    about: "VannDa appears as a featured artist on Kwan's 2024 single.",
    tags: ["featured", "2024"],
    sources: [WIKI],
  },
  {
    slug: "mesa-doch-may",
    title: "ដូចមេ (Like a Boss)",
    category: "featured",
    era: "global",
    releaseYear: 2024,
    releaseDateLabel: "February 23, 2024",
    primaryArtist: "Mesa",
    featuring: [],
    youtubeId: "9SAnqw-rIdI",
    youtubeChannel: "MESA - មេសា",
    about: "VannDa appears as a featured artist on Mesa's 2024 single, which he also produced.",
    tags: ["featured", "2024"],
    sources: [WIKI],
  },
  {
    slug: "vanthan-point-of-no-return",
    title: "មិនអាចវិលវិញ (Point of No Return)",
    category: "featured",
    era: "global",
    releaseYear: 2024,
    releaseDateLabel: "2024",
    primaryArtist: "Vanthan",
    featuring: [],
    youtubeId: "1IblrsqvB-Q",
    youtubeChannel: "Vanthan - វណ្ណថាន Official",
    about: "VannDa appears as a featured artist on this 2024 single by fellow Baramey artist Vanthan.",
    tags: ["featured", "2024", "baramey"],
    sources: [WIKI],
  },
  {
    slug: "norith-kromom-srok-na",
    title: "ក្រមុំស្រុកណា",
    category: "featured",
    era: "global",
    releaseYear: 2024,
    releaseDateLabel: "2024",
    durationSeconds: 291,
    primaryArtist: "Norith",
    featuring: [],
    youtubeId: "a2p9Ye-tpRM",
    youtubeChannel: "Norith - នរិទ្ធ",
    appleMusicUrl: "https://music.apple.com/us/album/%E1%9E%80-%E1%9E%9A%E1%9E%98-%E1%9E%9F-%E1%9E%9A-%E1%9E%80%E1%9E%8E-feat-vannda-single/1800354876",
    about: "VannDa appears as a featured artist on Norith's 2024 single.",
    tags: ["featured", "2024"],
    sources: [WIKI],
  },
  {
    slug: "zedes-sidequest",
    title: "Sidequest",
    category: "featured",
    era: "global",
    releaseYear: 2024,
    releaseDateLabel: "2024",
    durationSeconds: 174,
    primaryArtist: "Zedes",
    featuring: [],
    youtubeId: "lB9f1_cSdzU",
    youtubeChannel: "ZEDES",
    appleMusicUrl: "https://music.apple.com/us/song/sidequest-x-vannda/1771498272",
    about: "VannDa appears as a featured artist on Zedes's 2024 single.",
    tags: ["featured", "2024"],
    sources: [WIKI],
  },
  {
    slug: "vanthan-let-me-love-you",
    title: "ចែចង់ (Let Me Love You)",
    category: "featured",
    era: "current",
    releaseYear: 2025,
    releaseDateLabel: "2025",
    primaryArtist: "Vanthan",
    featuring: ["Norith"],
    youtubeId: "n3WX583RosA",
    youtubeChannel: "Vanthan - វណ្ណថាន Official",
    about: "VannDa and Norith both appear as featured artists on this Vanthan single.",
    tags: ["featured", "2025", "baramey"],
    sources: [{ label: "YouTube — Vanthan Official", url: "https://www.youtube.com/watch?v=n3WX583RosA" }],
  },

  // ───────────────────────── Early independent era (pre-Baramey) ─────────────────────────
  {
    slug: "y-o-u",
    title: "Y.O.U",
    category: "single",
    era: "independent",
    releaseYear: 2014,
    releaseDateLabel: "2014",
    featuring: [],
    youtubeId: "2P52pYbniPk",
    youtubeChannel: "វណ្ណដា-VannDa Official",
    about: "VannDa's earliest known independent release.",
    tags: ["single", "2014", "independent"],
    sources: [WIKI],
  },
  {
    slug: "hat",
    title: "ហត់",
    category: "single",
    era: "independent",
    releaseYear: 2016,
    releaseDateLabel: "2016",
    featuring: [],
    youtubeId: "c5vm0J2TweQ",
    youtubeChannel: "វណ្ណដា-VannDa Official",
    about: "An independent single from VannDa's pre-Baramey era.",
    tags: ["single", "2016", "independent"],
    sources: [WIKI],
  },
  {
    slug: "ke-cheak-anak-na",
    title: "គេជាអ្នកណា",
    category: "single",
    era: "independent",
    releaseYear: 2016,
    releaseDateLabel: "2016",
    featuring: [],
    youtubeId: "QT8rERkKORc",
    youtubeChannel: "វណ្ណដា-VannDa Official",
    about: "An independent single from VannDa's pre-Baramey era.",
    tags: ["single", "2016", "independent"],
    sources: [WIKI],
  },
  {
    slug: "chheu-te",
    title: "ឈឺទេ",
    category: "single",
    era: "independent",
    releaseYear: 2017,
    releaseDateLabel: "2017",
    featuring: [],
    youtubeId: "Zv92QLiLcYg",
    youtubeChannel: "វណ្ណដា-VannDa Official",
    about: "An independent single from VannDa's pre-Baramey era.",
    tags: ["single", "2017", "independent"],
    sources: [WIKI],
  },
  {
    slug: "back-in-the-day-2018",
    title: "Back In The Day",
    category: "single",
    era: "independent",
    releaseYear: 2018,
    releaseDateLabel: "2018",
    featuring: [],
    youtubeId: "Ac6OJxmiuJA",
    youtubeChannel: "វណ្ណដា-VannDa Official",
    about: "The original independent version of \"Back In The Day,\" later remade for $kull the Album (2020).",
    tags: ["single", "2018", "independent"],
    sources: [WIKI],
  },
  {
    slug: "start-and-stop",
    title: "ចាប់ផ្ដើម&បញ្ចប់ (Start & Stop)",
    category: "single",
    era: "independent",
    releaseYear: 2018,
    releaseDateLabel: "2018",
    featuring: [],
    youtubeId: "fYqq4245wvI",
    youtubeChannel: "វណ្ណដា-VannDa Official",
    about: "An independent single from VannDa's pre-Baramey era.",
    tags: ["single", "2018", "independent"],
    sources: [WIKI],
  },
];
