/**
 * Every entry here was checked with scripts/verify-youtube.mjs against YouTube's
 * public oEmbed endpoint. A video is only listed if either:
 *   (a) its channel exactly matched the OFFICIAL_CHANNELS allow-list in that
 *       script, or
 *   (b) the channel's own title unambiguously self-identifies as the artist's
 *       or label's official channel (e.g. "Vanthan - វណ្ណថាន Official",
 *       "Baramey Official") even though it didn't hit the exact-string match.
 * Fan reposts, reaction channels, remixes, and auto-generated "Topic" channels
 * are excluded regardless of view count.
 */
import type { VideoEntry } from "./types";

export const videos: VideoEntry[] = [
  {
    id: "time-to-rise",
    youtubeId: "rvje5oblrLw",
    title: "VannDa - Time To Rise feat. Master Kong Nay (Official Music Video)",
    category: "music-video",
    year: 2021,
    channel: "វណ្ណដា-VannDa Official",
    relatedSongSlug: "time-to-rise",
    sources: [{ label: "YouTube — VannDa Official", url: "https://www.youtube.com/watch?v=rvje5oblrLw" }],
  },
  {
    id: "sophia-kao-time",
    youtubeId: "_1sdvk_8bYk",
    title: "Sophia Kao - Time feat. VannDa (Official Music Video)",
    category: "collaboration",
    year: 2021,
    channel: "Sophia Kao",
    relatedSongSlug: "time",
    sources: [{ label: "YouTube — Sophia Kao", url: "https://www.youtube.com/watch?v=_1sdvk_8bYk" }],
  },
  {
    id: "monsoon",
    youtubeId: "yMx-jKePx98",
    title: "SONGHA, VANNDA - Monsoon (Official Music Video)",
    category: "collaboration",
    year: 2021,
    channel: "វណ្ណដា-VannDa Official",
    relatedSongSlug: "monsoon",
    sources: [{ label: "YouTube — VannDa Official", url: "https://www.youtube.com/watch?v=yMx-jKePx98" }],
  },
  {
    id: "mama",
    youtubeId: "WNL3zDgWZc0",
    title: "VannDa - ម្តាយ (MAMA) ft. ក្មេងខ្មែរ (Official Music Video)",
    category: "music-video",
    year: 2020,
    channel: "វណ្ណដា-VannDa Official",
    relatedSongSlug: "mama",
    sources: [{ label: "YouTube — VannDa Official", url: "https://www.youtube.com/watch?v=WNL3zDgWZc0" }],
  },
  {
    id: "young-man",
    youtubeId: "nHXLfMeNoLA",
    title: "VannDa - Young Man feat. OG Bobby (Official Music Video)",
    category: "collaboration",
    year: 2022,
    channel: "វណ្ណដា-VannDa Official",
    relatedSongSlug: "young-man",
    sources: [{ label: "YouTube — VannDa Official", url: "https://www.youtube.com/watch?v=nHXLfMeNoLA" }],
  },
  {
    id: "run-the-town",
    youtubeId: "UwE8RPbPmrI",
    title: "F.HERO x VannDa Ft. 1MILL & SPRITE - Run The Town (Official MV)",
    category: "collaboration",
    year: 2022,
    channel: "វណ្ណដា-VannDa Official",
    relatedSongSlug: "run-the-town",
    sources: [{ label: "YouTube — VannDa Official", url: "https://www.youtube.com/watch?v=UwE8RPbPmrI" }],
  },
  {
    id: "coda",
    youtubeId: "VYLM-vpdQ1A",
    title: "VannDa - C.O.D.A (Official Music Video)",
    category: "music-video",
    year: 2022,
    channel: "វណ្ណដា-VannDa Official",
    relatedSongSlug: "coda",
    sources: [{ label: "YouTube — VannDa Official", url: "https://www.youtube.com/watch?v=VYLM-vpdQ1A" }],
  },
  {
    id: "6-years-in-the-game",
    youtubeId: "UAoI1SyWprI",
    title: "VannDa - 6 Years In The Game ft. Awich (Official Music Video)",
    category: "collaboration",
    year: 2024,
    channel: "វណ្ណដា-VannDa Official",
    relatedSongSlug: "6-years-in-the-game",
    sources: [{ label: "YouTube — VannDa Official", url: "https://www.youtube.com/watch?v=UAoI1SyWprI" }],
  },
  {
    id: "out-of-my-mind",
    youtubeId: "aSOuRMyxdNA",
    title: "VannDa - Out Of My Mind (Official Audio)",
    category: "audio",
    year: 2025,
    channel: "វណ្ណដា-VannDa Official",
    relatedSongSlug: "out-of-my-mind",
    sources: [{ label: "YouTube — VannDa Official", url: "https://www.youtube.com/watch?v=aSOuRMyxdNA" }],
  },
  {
    id: "fishing",
    youtubeId: "R5Lx2xCwsJQ",
    title: "VannDa - Fishing (Official Audio)",
    category: "audio",
    year: 2025,
    channel: "វណ្ណដា-VannDa Official",
    relatedSongSlug: "fishing",
    sources: [{ label: "YouTube — VannDa Official", url: "https://www.youtube.com/watch?v=R5Lx2xCwsJQ" }],
  },
  {
    id: "no-disrespect",
    youtubeId: "7t0qrQ0o42M",
    title: "VannDa - No Disrespect (Official Music Video)",
    category: "music-video",
    year: 2025,
    channel: "វណ្ណដា-VannDa Official",
    relatedSongSlug: "no-disrespect",
    sources: [{ label: "YouTube — VannDa Official", url: "https://www.youtube.com/watch?v=7t0qrQ0o42M" }],
  },
  {
    id: "asian-state-of-mind",
    youtubeId: "QRnO04UwnM0",
    title: "Asian State of Mind (Prod. Diego Ave) — Lyric Video: VannDa",
    category: "collaboration",
    year: 2025,
    channel: "Awich",
    relatedSongSlug: "asian-state-of-mind",
    sources: [{ label: "YouTube — Awich (official)", url: "https://www.youtube.com/watch?v=QRnO04UwnM0" }],
  },
  {
    id: "khmer-gentlemen",
    youtubeId: "fJuJ6GW0UEk",
    title: "Vanthan x VannDa - កម្លោះស្រុកខ្មែរ (Khmer Gentlemen) [Official Video]",
    category: "collaboration",
    year: 2023,
    channel: "Vanthan - វណ្ណថាន Official",
    relatedSongSlug: "khmer-gentlemen",
    sources: [{ label: "YouTube — Vanthan Official", url: "https://www.youtube.com/watch?v=fJuJ6GW0UEk" }],
  },
  {
    id: "golden-land",
    youtubeId: "jFVfxBQjMFU",
    title: "VannDa - សុវណ្ណភូមិ (Golden Land) [Official Music Video]",
    category: "music-video",
    year: 2025,
    channel: "វណ្ណដា-VannDa Official",
    relatedSongSlug: "golden-land",
    sources: [{ label: "YouTube — VannDa Official", url: "https://www.youtube.com/watch?v=jFVfxBQjMFU" }],
  },
  {
    id: "sangkran-magic",
    youtubeId: "Cpo3DmbdCxs",
    title: "VannDa - សង្រ្កាន្តស្គាល់ស្នេហ៍ (Sangkran Magic) [Official Music Video]",
    category: "music-video",
    year: 2023,
    channel: "វណ្ណដា-VannDa Official",
    relatedSongSlug: "sangkran-magic",
    sources: [{ label: "YouTube — VannDa Official", url: "https://www.youtube.com/watch?v=Cpo3DmbdCxs" }],
  },
  {
    id: "baby-mama",
    youtubeId: "Jbt5dRYFOPo",
    title: "VannDa - Baby Mama (Official Music Video)",
    category: "music-video",
    year: 2022,
    channel: "វណ្ណដា-VannDa Official",
    relatedSongSlug: "baby-mama",
    sources: [{ label: "YouTube — VannDa Official", url: "https://www.youtube.com/watch?v=Jbt5dRYFOPo" }],
  },
  {
    id: "blue-story",
    youtubeId: "0jSgcE-sxeo",
    title: "VannDa - Blue Story (Official Video)",
    category: "music-video",
    year: 2023,
    channel: "វណ្ណដា-VannDa Official",
    relatedSongSlug: "blue-story",
    sources: [{ label: "YouTube — VannDa Official", url: "https://www.youtube.com/watch?v=0jSgcE-sxeo" }],
  },
  {
    id: "day-dreamer",
    youtubeId: "KyrXi-q2bBY",
    title: "VannDa - សុបិនទាំងថ្ងៃ (Day Dreamer) [Official Music Video]",
    category: "music-video",
    year: 2023,
    channel: "វណ្ណដា-VannDa Official",
    relatedSongSlug: "day-dreamer",
    sources: [{ label: "YouTube — VannDa Official", url: "https://www.youtube.com/watch?v=KyrXi-q2bBY" }],
  },
  {
    id: "legacy-baramey-crew",
    youtubeId: "StNAenr4rVY",
    title: "Baramey Crew - ចងចាំសាវតារ (Legacy) [Official Audio]",
    category: "collaboration",
    year: 2023,
    channel: "Baramey Official",
    relatedSongSlug: "legacy",
    sources: [{ label: "YouTube — Baramey Official", url: "https://www.youtube.com/watch?v=StNAenr4rVY" }],
  },
];
